Lots of fixes.

diff --git a/appdir/znx-gui b/appdir/znx-gui
--- a/appdir/znx-gui
+++ b/appdir/znx-gui
@@ -1,88 +1,47 @@
-#! /bin/bash
+#! /bin/sh
 
 
 # -- Variables.
 
-TITLE=ZNX GUI
+TITLE=ZNX_GUI
 STYLE=breeze
 
 
-# -- Functions.
+# -- Functions for the GUI.
 
-error () {
-	printf "znx-gui: \e[31mError:\e[0m $@\n" >& 2
+alias ui="kdialog --style=$STYLE --title='$TITLE'"
 
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--error "$@"
+error () { ui --error "$@"; exit 1; }
+notify () { ui --passivepopup "$@" 5; }
+ask () { ui --yesno "$@"; }
+as_root () { ui --password "Password:" | sudo -Sk $@; }
 
-	exit 1
-}
+CMDS="init restore-esp deploy update revert remove clean reset stats"
 
-select_device () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--combobox "Select a device." $(lsblk -npdlo NAME)
-}
+select_command () { ui --combobox "Command to run:" $CMDS; }
+select_device () { ui --combobox "Device:" $(lsblk -npdlo NAME); }
+select_image () { ui --combobox "Image:" $(as_root ./znx list $DEVICE); }
 
-select_image () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--combobox "Select an image." $(pkexec znx list $DEVICE)
-}
+get_url () { ui --inputbox "File to deploy (URL or path):"; }
+get_image () { ui --inputbox "Image name:"; }
 
-select_command () {
-	CMDS="update revert remove clean"
 
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--combobox "Select an operation to perform over the image." $CMDS
-}
+# -- Wrappers for znx's commands.
 
-ask_for_deployment () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--yesno "Do you want to deploy an image?"
-}
+_znx_gui_init () { as_root ./znx init $DEVICE; }
+_znx_gui_restore-esp () { as_root ./znx restore-esp $DEVICE; }
+_znx_gui_deploy () { as_root ./znx deploy $DEVICE $(get_image) $(get_url); }
+_znx_gui_update () { as_root ./znx update $DEVICE $(select_image); }
+_znx_gui_revert () { as_root ./znx revert $DEVICE $(select_image); }
+_znx_gui_remove () { as_root ./znx remove $DEVICE $(select_image); }
+_znx_gui_clean () { as_root ./znx clean $DEVICE $(select_image); }
+_znx_gui_reset () { as_root ./znx reset $DEVICE $(select_image); }
 
-get_url () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--inputbox "Please provide the location of the image to deploy (URL or path)."
-}
-
-get_image_name () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--inputbox "Please provide a name for this image."
-}
-
-ask_for_device_initialization () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--yesno "$DEVICE has not been initialized yet. Would you like to initialize it?"
-}
-
-notify () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--passivepopup "$@" 5
-}
-
-as_root () {
-	kdialog \
-		--style $STYLE \
-		--title $TITLE \
-		--password "Password:" | sudo -Sk $@
+_znx_gui_stats () {
+	TMP_FILE=$(mktemp)
+	as_root ./znx stats $DEVICE $(select_image) > $TMP_FILE
+	ui --textbox $TMP_FILE
+	rm -rf $TMP_FILE
 }
 
 
@@ -90,65 +49,20 @@ as_root () {
 
 while :; do
 
-	# -- Choose the device.
+	COMMAND=$(select_command)
 
-	DEVICE=
+	[ ${#COMMAND} -gt 0 ] ||
+		error "Operation cancelled."
+
+	notify "Please wait. You will be notified when the command finishes."; 
+
 	DEVICE=$(select_device)
 
+	_znx_gui_$COMMAND &&
+		notify "Operation completed successfully." ||
+		error "Operation failed!"
 
-	# -- If the user cancelled the previous step, then exit.
-
-	[ ${#DEVICE} -eq 0 ] &&
+	ask "Do you want to perform another action?" ||
 		exit
-
-
-	# -- Check if the device has been initialized.
-
-	blkid $DEVICE* | grep -q ZNX_DATA || {
-
-		ask_for_device_initialization &&
-			COMMAND=init
-
-	} && {
-
-		# -- The device is initialized. Show the available images.
-
-		ask_for_deployment && {
-
-			COMMAND=
-			COMMAND=deploy
-
-			URL=
-			URL=$(get_url)
-
-			IMAGE=
-			IMAGE=$(get_image_name)
-
-		} || {
-
-			IMAGE=
-			IMAGE=$(select_image)
-
-			[ ${#IMAGE} -eq 0 ] &&
-				continue
-
-			COMMAND=
-			COMMAND=$(select_command)
-
-			[ ${#COMMAND} -eq 0 ] &&
-				continue
-
-		}
-
-	}
-
-
-	# -- Run the desired command.
-
-	notify "Please wait. You will be notified the command finishes."
-
-	as_root znx $COMMAND $DEVICE $IMAGE $URL &&
-		notify "Operation completed with success." ||
-		notify "Operation failed!"
 
 done
